import { Plus_Jakarta_Sans } from 'next/font/google';import "./globals.css";
import Header from "./components/Header";
  import BackgroundWrapper from "./components/backgroundWrap";
const jakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-jakarta', // Connects it cleanly to your system variable
});
export const metadata = {
  title: "ECBI",
  description: "Generated by create next app",
};
   
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`scroll-smooth ${jakartaSans.variable}`}>
      
         <body className="font-sans antialiased bg-slate-50 text-slate-900 ">
          <div className="flex ">
              <Header/>
          <main className="flex-1  min-h-[100vh] mx-auto">
          
           
                <BackgroundWrapper>
                 

      {children} 
      </BackgroundWrapper>
          
           


          </main>
          </div>
         
        
        <footer>
          {/* <p>copy right 2023</p>
          <p>created by lenovo</p>
          <p>powered by next.js</p>
          <p>made with love</p> */}

        </footer>
      
      </body>
     
     
    </html>
  );
}
