import { Plus_Jakarta_Sans } from 'next/font/google';import "./globals.css";
import Header from "./components/Header";
  import BackgroundWrapper from "./components/backgroundWrap";
const jakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-jakarta', // Connects it cleanly to your system variable
});
export const metadata = {
  title: "ECBI",
  description: "Generated by create next app",
};
   
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`scroll-smooth ${jakartaSans.variable}`}>
      
     <body className="font-sans antialiased bg-slate-50 text-slate-900">
  <div className="flex min-h-screen">
    <Header />

    <main className="flex-1 w-full">
      <BackgroundWrapper>
        {children}
      </BackgroundWrapper>
    </main>
  </div>
</body>
     
     
    </html>
  );
}
